package com.prova.db.prova_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE OrderBase PLEASE EDIT ../Order.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Order object
 * 
 */
 
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import java.util.Date;
import java.util.List;

import org.mongodb.morphia.annotations.Id;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.prova.utils.ObjectIdListSerializer;


//IMPORT RELATIONS
import com.prova.db.prova_db.entity.Product;
import com.prova.db.prova_db.entity.User;

@Entity("Order")
public class OrderBase {
	
	@Id
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId _id;
	
	// Attributes
	private Date  date;
	private   total;
	
	
	// Relations user
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId user;
	
	
	
	// Relations m:m product
	@JsonSerialize(using = ObjectIdListSerializer.class)
	private List<ObjectId> product;
	
	

    // GETTER AND SETTER
    
	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId id) {
		this._id = id;
	}


	public Date getDate() {
		return date;
	}


	public void setDate(Date date) {
		this.date = date;
	}
	public  getTotal() {
		return total;
	}


	public void setTotal( total) {
		this.total = total;
	}

	
    
    // Relations 1:m user
	public ObjectId getUser() {
		return user;
	}

	public void setUser(ObjectId user) {
		this.user = user;
	}
    
    
    
    
    // Relations m:m product
	public List<ObjectId> getProduct() {
		return product;
	}

	public void setProduct(List<ObjectId> product) {
		this.product = product;
	}
	
    
}